
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
variables:
  IMAGE_NAME: git.cs.kent.ac.uk/jwb50/final-year-project-manager
  DOCKER_HOST: tcp://docker:2375

docker:image:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker version
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:latest
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest

    # This job runs in the deploy stage.
deploy:
  stage: deploy
  image: alpine/helm:3.9.1
  tags:
    - preprod
    - kubernetes
  script:
    - helm upgrade final-year-project-manager ./deploy --install --set-string image.tag=${CI_COMMIT_SHORT_SHA} --namespace final-year-project-manager --timeout 30m0s


