
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
variables:
  IMAGE_NAME: git.cs.kent.ac.uk/jwb50/final-year-project-manager
  DOCKER_HOST: tcp://localhost:2375/ #Not sure this is right

build:      # This job runs in the build stage, which runs first.
  stage: build
  image: docker:18-git
  services:
    - docker:18-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN https://git.cs.kent.ac.uk/jwb50/final-year-project-manager/
    - docker build -f Dockerfile --tag ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA} .
    - docker push ${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}

    # This job runs in the deploy stage.
deploy:
  stage: deploy
  image: alpine/helm:3.5.4
  tags:
    - preprod
    - kubernetes
  script:
    - helm upgrade final-year-project-manager ./deploy --install --set-string image.tag=${CI_COMMIT_SHORT_SHA} --namespace final-year-project-manager --timeout 30m0s


