variables:
  IMAGE_NAME: git.cs.kent.ac.uk/jwb50/final-year-project-manager
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:          # List of stages for jobs, and their order of execution
  - build
  - build
  - build
  - build
  - build
# - deploy

docker:backend:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker version
    - docker build -t $CI_REGISTRY_IMAGE:latest_RegForm_backend .
    - docker tag $CI_REGISTRY_IMAGE:latest_RegForm_backend $CI_REGISTRY_IMAGE:latest_RegForm_backend
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest_RegForm_backend

docker:frontend:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker version
    - docker build -f src/regForm/Dockerfile -t $CI_REGISTRY_IMAGE:latest_RegForm_frontend .
    - docker tag $CI_REGISTRY_IMAGE:latest_RegForm_frontend $CI_REGISTRY_IMAGE:latest_RegForm_frontend
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest_RegForm_frontend


docker:login:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker version
    - docker build -f src/login/Dockerfile -t $CI_REGISTRY_IMAGE:latest_login_frontend .
    - docker tag $CI_REGISTRY_IMAGE:latest_login_frontend $CI_REGISTRY_IMAGE:latest_login_frontend
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest_login_frontend

docker:psPage:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker version
    - docker build -f src/login/Dockerfile -t $CI_REGISTRY_IMAGE:latest_psPage_frontend .
    - docker tag $CI_REGISTRY_IMAGE:latest_psPage_frontend $CI_REGISTRY_IMAGE:latest_psPage_frontend
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest_psPage_frontend

docker:excelReader:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker version
    - docker build -f src/login/Dockerfile -t $CI_REGISTRY_IMAGE:latest_psPage_excelReader .
    - docker tag $CI_REGISTRY_IMAGE:latest_psPage_excelReader $CI_REGISTRY_IMAGE:latest_psPage_excelReader
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:latest_psPage_excelReader


#deploy:
#   stage: deploy
#    image: alpine/helm:3.9.1
#  tags:
#    - preprod
#    - kubernetes
#  script:
#    - helm upgrade final-year-project-manager ./deploy --install --set-string #image.tag=${CI_COMMIT_SHORT_SHA} --namespace final-year-project-manager --timeout #30m0s


