concurrent = 1
check_interval = 0

[[runners]]
  name = "fyp-runner"
  url = "https://git.cs.kent.ac.uk/jwb50/final-year-project-manager/"
  token = "GR1348941mBxwsi5EsX_hXy3k3KNy"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "alpine:3.4"
    privileged = true
    disable_cache = false
    volumes = ["/cache"]
  [runners.cache]
    Insecure = false


