apiVersion: v1
kind: Service
metadata:
  name: regform
spec:
  selector:
    app: regform
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regform
spec:
  selector:
    matchLabels:
      app: regform
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: regform
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "git.cs.kent.ac.uk:5050/jwb50/final-year-project-manager:latest_RegForm_frontend"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]