version: '3'

services:
  Login:
    image: nginx:latest
    volumes:
      - ./src:/usr/share/nginx/html
      # - ./site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - "8082:80"

  # php:
  #   image: php:7-fpm
  #   volumes:
  #     - ./src:/src